### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by zeroXBami** [PacktPublishing/Blockchain-for-Enterprise#1]
Hi,

I am following your instruction but got this error when start node via cmd: 
PRIVATE_CONFIG=constellation1.conf ./geth --datadir qdata/node1 --port 23000 --raftport 30301 --raft --ipcpath "./geth.ipcc"
ERROR:
panic: MustNew: Failed to connect to Constellation (constellation1.conf): Get http+unix://c/upcheck: dial unix cnode_data/cnode1/constellation_node1.ipc: connect: connection refused

Could you please help?

**Comment by suwarnarajput** [comment]
Hello team,



I have done the changes in command please ask reader to use the following command:


PRIVATE_CONFIG=constellation1.conf ./geth --datadir qdata/node1 --port 23000 --raftport 30301 --raft --ipcpath "./geth.ipc"


Thanks and regards,
Suwarna


________________________________

**Comment by githubce** [comment]
Hi @trnhgquan 

Please follow the updated command in order to eliminate this error.
You may reopen this issue in case you are having any further issues.

Regards,
